### PR TITLE
Function result contains resulting XML as attribute, with support for normalization using xmllint options --format and --c14n

### PR DESCRIPTION
**Pull request by fhaftmann**
The subject tells the core of the story.

To facilitate the implementation of that extension and maintenance of the existing code base, the library logic proper has been centralized in index.js, reducing auxiliary steps in the generated wasm wrapper and the worker module to the baremost minimum.

### CODE REVIEW

**Comment by noppa** [comment]
Hey, thanks a lot for your contribution!  
I'm not familiar with these options to xmllint, but I'll take a closer look in a few days. On a quick glance the code looks fine.

Although, there are quite a bit of changes that seem unrelated to the actual implementation of the features. I don't have anything against a good refactoring per se, but just a heads up that it does add more stuff to review and thus slows down the process a bit and may sometimes lead to requests to change the code before it can merged.

Anyway, I do appriciate this and will try to review this asap. Thanks again

**Comment by fhaftmann** [comment]
Concerning reviewing the refactoring, it is best to follow the history commit by commit; they are supposed to be self-contained.

**Comment by noppa** [comment]
I have released this under version 2.1.0-beta.0 (install via `npm i xmllint-wasm@beta`). I'll make a proper non-beta release in a few days after testing it out a bit. 

Thanks!

**Comment by noppa** [comment]
@fhaftmann FYI [I made one change to this](https://github.com/noppa/xmllint-wasm/commit/c74fdbe94781a3adf06c1de0c26a55d62b2b6707): we'll still pass `--noout` by default if the normalization option isn't set. I don't see how xmllint's default behavior of outputting the same XML back would be useful to anyone and it does come with a perf/memory cost when the input XML is large.

**Comment by fhaftmann** [comment]
@noppa Of course that makes perfectly sense. Thanks for looking through that thoroughly.

**Pull request merged**
